# Generated by Django 2.2.17 on 2020-12-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('pseudo', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=40)),
                ('est_actif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=2)),
                ('etat', models.CharField(max_length=150)),
                ('type_facturation', models.CharField(max_length=100)),
                ('est_actif', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gererPanier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=2)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('est_actif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produit', models.IntegerField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gererPanier.Commande')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gererPanier.Produit')),
            ],
        ),
    ]
