# Generated by Django 2.2.17 on 2020-12-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gererPanier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeproduit',
            name='id_commande',
        ),
        migrations.RemoveField(
            model_name='commandeproduit',
            name='id_produit',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='CommandeProduit',
        ),
    ]
