# Generated by Django 2.2.17 on 2020-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gererPanier', '0002_auto_20201217_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
