# Generated by Django 2.2.17 on 2020-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gererPanier', '0003_auto_20201217_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_de_naissance',
            field=models.CharField(max_length=20),
        ),
    ]
