# Generated by Django 2.2.17 on 2020-12-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gererPanier', '0006_auto_20201228_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
